version: '3'

services :

  postgresql :
    container_name: POSTGRES
    image: postgres:alpine
    ports :
     - "54320:5432"
    environment:
      - POSTGRES_USER=of_dck
      - POSTGRES_PASSWORD=gft78kP9!luY!
      - POSTGRES_DB=onlyfeed
    volumes :
      - ./postgres/init_onlyfeed_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/pgdata:/var/lib/postgresql/data
    network_mode: host

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ZOOKKEPER
    restart: always
    ports:
      - 2181:218
    network_mode: host

  kafka:
    image: wurstmeister/kafka
    container_name: KAFKA
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: debian
      KAFKA_ZOOKEEPER_CONNECT: debian:2181
      KAFKA_CREATE_TOPICS: "review:1:1"
    network_mode: host