version: '3'

services :

  postgresql :
    container_name: POSTGRES
    image: postgres:alpine
    ports :
     - "54320:5432"
    environment:
      - POSTGRES_USER=of_dck
      - POSTGRES_PASSWORD=gft78kP9!luY!
      - POSTGRES_DB=onlyfeed
    volumes :
      - ./postgres/init_onlyfeed_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/pgdata:/var/lib/postgresql/data
    network_mode: host